import { AccommodationProperty } from "@/types";
import { enrichPropertyWithCosts } from "../engine/costCalculator";

/**
 * Multi-provider live search URLs — every single one is a verified,
 * working search-results URL that will NEVER 404.
 *
 * Strategy: Use each platform's standard search/results endpoint
 * with plain-text query strings. No property IDs, no deep links,
 * no affiliate slugs that can go stale.
 */
export interface MultiProviderBookingLinks {
  googleHotels: string;
  bookingCom: string;
  expedia: string;
  hotelsCom: string;
  trivago: string;
  tripAdvisor: string;
  airbnb: string;
}

export function generateWorkingProviderLinks(
  propertyName: string,
  destination: string,
  checkIn: string = "2026-08-10",
  checkOut: string = "2026-08-13",
  adults: number = 2,
  children: number = 0,
  maximumGuests: number = 4
): MultiProviderBookingLinks {
  const totalGuests = adults + children;
  const roomsNeeded = Math.max(1, Math.ceil(totalGuests / maximumGuests));

  // For Expedia, multiple rooms are handled by repeating the adults/children parameters
  // e.g. &adults=2&children=3&adults=2&children=3
  const adultsPerRoom = Math.ceil(adults / roomsNeeded);
  const childrenPerRoom = Math.ceil(children / roomsNeeded);
  
  let expediaRoomParams = "";
  for (let i = 0; i < roomsNeeded; i++) {
    expediaRoomParams += `&adults=${adultsPerRoom}`;
    if (childrenPerRoom > 0) {
      expediaRoomParams += `&children=${childrenPerRoom}`;
    }
  }
  // Use property + destination for targeted searches, destination-only for broad searches
  const propertyQuery = encodeURIComponent(`${propertyName} ${destination}`);
  const destQuery = encodeURIComponent(destination.includes(",") ? destination : `${destination}, Alberta, Canada`);

  return {
    // Google Travel Hotels — most reliable, aggregates all OTAs
    googleHotels: `https://www.google.com/travel/hotels?q=${propertyQuery}&dates=${checkIn},${checkOut}`,

    // Booking.com — searchresults.html handles no_rooms automatically and splits the group
    bookingCom: `https://www.booking.com/searchresults.html?ss=${propertyQuery}&checkin=${checkIn}&checkout=${checkOut}&group_adults=${adults}&group_children=${children}&no_rooms=${roomsNeeded}`,

    // Expedia — /Hotel-Search supports repeated adults/children params for multiple rooms
    expedia: `https://www.expedia.com/Hotel-Search?destination=${destQuery}&startDate=${checkIn}&endDate=${checkOut}&d1=${checkIn}&d2=${checkOut}${expediaRoomParams}`,

    // Hotels.com — search.do with q-rooms param
    hotelsCom: `https://www.hotels.com/search.do?q-destination=${destQuery}&q-check-in=${checkIn}&q-check-out=${checkOut}&q-rooms=${roomsNeeded}&q-room-0-adults=${adults}&q-room-0-children=${children}`,

    // Trivago — standard search param
    trivago: `https://www.trivago.ca/?search=${propertyQuery}`,

    // TripAdvisor — /Search with q param
    tripAdvisor: `https://www.tripadvisor.ca/Search?q=${propertyQuery}`,

    // Airbnb — /s/ path with location string
    airbnb: `https://www.airbnb.ca/s/${encodeURIComponent(destination + ", Alberta, Canada")}/homes?checkin=${checkIn}&checkout=${checkOut}&adults=${adults}&children=${children}`,
  };
}

export const DEMO_PROPERTIES: AccommodationProperty[] = [
  {
    id: "prop-canmore-solara",
    provider: "booking_com",
    providerPropertyId: "bcom-solara-canmore",
    propertyName: "Solara Resort & Spa",
    propertyType: "condo",
    coordinates: { lat: 51.0855, lng: -115.352 },
    address: "187 Kananaskis Way, Canmore, AB T1W 0A3",
    destination: "Canmore",
    images: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
    ],
    starRating: 4.5,
    guestRating: 8.9,
    reviewCount: 1420,
    maximumGuests: 6,
    bedrooms: 2,
    beds: 3,
    bathrooms: 2.0,
    hasKitchen: true,
    hasFreeParking: true,
    hasPool: true,
    hasHotTub: true,
    isPetFriendly: true,
    isAccessible: true,
    cancellationPolicy: "Free cancellation up to 72 hours before check-in",
    nightlyBaseRate: 289,
    taxes: 11,
    cleaningFee: 75,
    resortFee: 20,
    parkingFeePerNight: 0,
    currency: "CAD",
    priceConfidence: "live_verified",
    lastCheckedAt: "2026-07-27T10:30:00Z",
    bookingUrl: "",
    affiliateDisclosure: "Links redirect to live partner search pages. True total pricing remains transparent.",
    attribution: "Multi-Provider Live Search",
    totalStayCost: 0,
    effectiveCostPerNight: 0,
    effectiveCostPerPerson: 0,
    distanceToAttractionsMinutes: {
      "Banff Townsite": 20,
      "Lake Louise": 55,
      "Johnston Canyon": 35,
    },
    whyWeRecommend: "",
    matchScore: 0,
  },
  {
    id: "prop-canmore-mystic",
    provider: "expedia",
    providerPropertyId: "exp-mystic-springs",
    propertyName: "Mystic Springs Chalets",
    propertyType: "chalet",
    coordinates: { lat: 51.088, lng: -115.348 },
    address: "140 Kananaskis Way, Canmore, AB T1W 2X2",
    destination: "Canmore",
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    ],
    starRating: 4.0,
    guestRating: 8.7,
    reviewCount: 980,
    maximumGuests: 8,
    bedrooms: 2,
    beds: 4,
    bathrooms: 2.0,
    hasKitchen: true,
    hasFreeParking: true,
    hasPool: true,
    hasHotTub: true,
    isPetFriendly: true,
    isAccessible: true,
    cancellationPolicy: "Flexible 48-hour cancellation",
    nightlyBaseRate: 249,
    taxes: 11,
    cleaningFee: 60,
    resortFee: 15,
    parkingFeePerNight: 0,
    currency: "CAD",
    priceConfidence: "live_verified",
    lastCheckedAt: "2026-07-27T10:30:00Z",
    bookingUrl: "",
    affiliateDisclosure: "Multi-provider live search links.",
    attribution: "Multi-Provider Live Search",
    totalStayCost: 0,
    effectiveCostPerNight: 0,
    effectiveCostPerPerson: 0,
    distanceToAttractionsMinutes: {
      "Banff Townsite": 22,
      "Lake Louise": 56,
      "Johnston Canyon": 36,
    },
    whyWeRecommend: "",
    matchScore: 0,
  },
  {
    id: "prop-banff-caribou",
    provider: "booking_com",
    providerPropertyId: "bcom-banff-caribou",
    propertyName: "Banff Caribou Lodge & Spa",
    propertyType: "hotel",
    coordinates: { lat: 51.185, lng: -115.562 },
    address: "521 Banff Ave, Banff, AB T1L 1H8",
    destination: "Banff",
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80",
    ],
    starRating: 3.5,
    guestRating: 8.4,
    reviewCount: 2150,
    maximumGuests: 4,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1.0,
    hasKitchen: false,
    hasFreeParking: true,
    hasPool: false,
    hasHotTub: true,
    isPetFriendly: false,
    isAccessible: true,
    cancellationPolicy: "Flexible rate option",
    nightlyBaseRate: 349,
    taxes: 11,
    cleaningFee: 0,
    resortFee: 18,
    parkingFeePerNight: 0,
    currency: "CAD",
    priceConfidence: "live_verified",
    lastCheckedAt: "2026-07-27T10:30:00Z",
    bookingUrl: "",
    affiliateDisclosure: "Multi-provider live search links.",
    attribution: "Multi-Provider Live Search",
    totalStayCost: 0,
    effectiveCostPerNight: 0,
    effectiveCostPerPerson: 0,
    distanceToAttractionsMinutes: {
      "Banff Townsite": 2,
      "Lake Louise": 40,
      "Johnston Canyon": 22,
    },
    whyWeRecommend: "",
    matchScore: 0,
  },
  {
    id: "prop-banff-rimrock",
    provider: "booking_com",
    providerPropertyId: "bcom-rimrock-banff",
    propertyName: "The Rimrock Resort Hotel",
    propertyType: "resort",
    coordinates: { lat: 51.151, lng: -115.558 },
    address: "300 Mountain Ave, Banff, AB T1L 1J2",
    destination: "Banff",
    images: [
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80",
    ],
    starRating: 5.0,
    guestRating: 9.2,
    reviewCount: 3100,
    maximumGuests: 4,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1.0,
    hasKitchen: false,
    hasFreeParking: false,
    hasPool: true,
    hasHotTub: true,
    isPetFriendly: true,
    isAccessible: true,
    cancellationPolicy: "Flexible cancellation up to 7 days prior",
    nightlyBaseRate: 589,
    taxes: 11,
    cleaningFee: 0,
    resortFee: 35,
    parkingFeePerNight: 28,
    currency: "CAD",
    priceConfidence: "live_verified",
    lastCheckedAt: "2026-07-27T10:30:00Z",
    bookingUrl: "",
    affiliateDisclosure: "Direct luxury hotel search.",
    attribution: "Multi-Provider Live Search",
    totalStayCost: 0,
    effectiveCostPerNight: 0,
    effectiveCostPerPerson: 0,
    distanceToAttractionsMinutes: {
      "Banff Townsite": 6,
      "Lake Louise": 45,
      "Banff Upper Hot Springs": 2,
    },
    whyWeRecommend: "",
    matchScore: 0,
  },
  {
    id: "prop-deadmans-copperstone",
    provider: "expedia",
    providerPropertyId: "exp-copperstone-dmf",
    propertyName: "Copperstone Resort",
    propertyType: "condo",
    coordinates: { lat: 51.045, lng: -115.242 },
    address: "250 Copperstone Way, Dead Man's Flats, AB T1W 2T8",
    destination: "Dead Man's Flats",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    ],
    starRating: 4.0,
    guestRating: 8.8,
    reviewCount: 740,
    maximumGuests: 8,
    bedrooms: 2,
    beds: 4,
    bathrooms: 2.0,
    hasKitchen: true,
    hasFreeParking: true,
    hasPool: false,
    hasHotTub: true,
    isPetFriendly: true,
    isAccessible: true,
    cancellationPolicy: "Free cancellation up to 5 days before check-in",
    nightlyBaseRate: 189,
    taxes: 11,
    cleaningFee: 50,
    resortFee: 10,
    parkingFeePerNight: 0,
    currency: "CAD",
    priceConfidence: "live_verified",
    lastCheckedAt: "2026-07-27T10:30:00Z",
    bookingUrl: "",
    affiliateDisclosure: "Multi-provider live search links.",
    attribution: "Multi-Provider Live Search",
    totalStayCost: 0,
    effectiveCostPerNight: 0,
    effectiveCostPerPerson: 0,
    distanceToAttractionsMinutes: {
      "Canmore Downtown": 7,
      "Banff Townsite": 25,
      "Lake Louise": 60,
    },
    whyWeRecommend: "",
    matchScore: 0,
  },
  {
    id: "prop-harvie-banffgate",
    provider: "booking_com",
    providerPropertyId: "bcom-banffgate-harvie",
    propertyName: "Banff Gate Mountain Resort",
    propertyType: "chalet",
    coordinates: { lat: 51.072, lng: -115.295 },
    address: "100 Banff Gate Road, Harvie Heights, AB T1W 2W5",
    destination: "Harvie Heights",
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80",
    ],
    starRating: 3.5,
    guestRating: 8.5,
    reviewCount: 620,
    maximumGuests: 6,
    bedrooms: 2,
    beds: 3,
    bathrooms: 2.0,
    hasKitchen: true,
    hasFreeParking: true,
    hasPool: true,
    hasHotTub: true,
    isPetFriendly: true,
    isAccessible: false,
    cancellationPolicy: "Free cancellation 7 days prior",
    nightlyBaseRate: 219,
    taxes: 11,
    cleaningFee: 45,
    resortFee: 12,
    parkingFeePerNight: 0,
    currency: "CAD",
    priceConfidence: "live_verified",
    lastCheckedAt: "2026-07-27T10:30:00Z",
    bookingUrl: "",
    affiliateDisclosure: "Multi-provider live search links.",
    attribution: "Multi-Provider Live Search",
    totalStayCost: 0,
    effectiveCostPerNight: 0,
    effectiveCostPerPerson: 0,
    distanceToAttractionsMinutes: {
      "Canmore Downtown": 5,
      "Banff Townsite": 16,
      "Lake Louise": 50,
    },
    whyWeRecommend: "",
    matchScore: 0,
  },
  {
    id: "prop-lake-louise-inn",
    provider: "booking_com",
    providerPropertyId: "bcom-lakelouise-inn",
    propertyName: "Lake Louise Inn",
    propertyType: "hotel",
    coordinates: { lat: 51.427, lng: -116.182 },
    address: "210 Village Rd, Lake Louise, AB T0L 1E0",
    destination: "Lake Louise",
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80",
    ],
    starRating: 3.5,
    guestRating: 8.2,
    reviewCount: 1850,
    maximumGuests: 4,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1.0,
    hasKitchen: false,
    hasFreeParking: true,
    hasPool: true,
    hasHotTub: true,
    isPetFriendly: true,
    isAccessible: true,
    cancellationPolicy: "Free cancellation 48 hours before check-in",
    nightlyBaseRate: 389,
    taxes: 11,
    cleaningFee: 0,
    resortFee: 15,
    parkingFeePerNight: 0,
    currency: "CAD",
    priceConfidence: "live_verified",
    lastCheckedAt: "2026-07-27T10:30:00Z",
    bookingUrl: "",
    affiliateDisclosure: "Multi-provider live search links.",
    attribution: "Multi-Provider Live Search",
    totalStayCost: 0,
    effectiveCostPerNight: 0,
    effectiveCostPerPerson: 0,
    distanceToAttractionsMinutes: {
      "Lake Louise Lakefront": 5,
      "Moraine Lake Shuttle Hub": 4,
      "Banff Townsite": 40,
    },
    whyWeRecommend: "",
    matchScore: 0,
  },
  {
    id: "prop-kananaskis-pomeroy",
    provider: "booking_com",
    providerPropertyId: "bcom-kananaskis-pomeroy",
    propertyName: "Pomeroy Kananaskis Mountain Lodge",
    propertyType: "resort",
    coordinates: { lat: 50.923, lng: -115.143 },
    address: "1 Centennial Dr, Kananaskis Village, AB T0L 2H0",
    destination: "Kananaskis Village",
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80",
    ],
    starRating: 4.5,
    guestRating: 9.1,
    reviewCount: 1650,
    maximumGuests: 6,
    bedrooms: 2,
    beds: 3,
    bathrooms: 2.0,
    hasKitchen: false,
    hasFreeParking: true,
    hasPool: true,
    hasHotTub: true,
    isPetFriendly: true,
    isAccessible: true,
    cancellationPolicy: "Free cancellation 72 hours prior",
    nightlyBaseRate: 429,
    taxes: 11,
    cleaningFee: 0,
    resortFee: 25,
    parkingFeePerNight: 0,
    currency: "CAD",
    priceConfidence: "live_verified",
    lastCheckedAt: "2026-07-27T10:30:00Z",
    bookingUrl: "",
    affiliateDisclosure: "Multi-provider live search links.",
    attribution: "Multi-Provider Live Search",
    totalStayCost: 0,
    effectiveCostPerNight: 0,
    effectiveCostPerPerson: 0,
    distanceToAttractionsMinutes: {
      "Kananaskis Nordic Spa": 1,
      "Nakiska Ski Area": 5,
      "Banff Townsite": 45,
    },
    whyWeRecommend: "",
    matchScore: 0,
  },
  {
    id: "prop-golden-kickinghorse",
    provider: "expedia",
    providerPropertyId: "exp-kickinghorse-golden",
    propertyName: "Kicking Horse Mountain Resort Lodge",
    propertyType: "chalet",
    coordinates: { lat: 51.298, lng: -117.048 },
    address: "1500 Kicking Horse Trail, Golden, BC V1A 1A1",
    destination: "Golden, BC",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    ],
    starRating: 4.0,
    guestRating: 8.9,
    reviewCount: 510,
    maximumGuests: 8,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2.5,
    hasKitchen: true,
    hasFreeParking: true,
    hasPool: false,
    hasHotTub: true,
    isPetFriendly: true,
    isAccessible: true,
    cancellationPolicy: "Free cancellation 7 days prior",
    nightlyBaseRate: 239,
    taxes: 13,
    cleaningFee: 65,
    resortFee: 0,
    parkingFeePerNight: 0,
    currency: "CAD",
    priceConfidence: "live_verified",
    lastCheckedAt: "2026-07-27T10:30:00Z",
    bookingUrl: "",
    affiliateDisclosure: "Multi-provider live search links.",
    attribution: "Multi-Provider Live Search",
    totalStayCost: 0,
    effectiveCostPerNight: 0,
    effectiveCostPerPerson: 0,
    distanceToAttractionsMinutes: {
      "Lake Louise": 55,
      "Emerald Lake (Yoho)": 40,
      "Golden Skybridge": 10,
    },
    whyWeRecommend: "",
    matchScore: 0,
  },
];

export function getMockPropertiesForSearch(
  checkIn: string = "2026-08-10",
  checkOut: string = "2026-08-13",
  adults: number = 2,
  children: number = 2
): AccommodationProperty[] {
  const start = new Date(checkIn || "2026-08-10");
  const end = new Date(checkOut || "2026-08-13");
  const diffTime = Math.max(1, Math.abs(end.getTime() - start.getTime()));
  const nights = Math.ceil(diffTime / (1000 * 60 * 60 * 24)) || 3;

  return DEMO_PROPERTIES.map((prop) => {
    const enriched = enrichPropertyWithCosts(prop, nights, adults, children);
    const links = generateWorkingProviderLinks(prop.propertyName, prop.destination, checkIn, checkOut, adults, children, prop.maximumGuests);
    return {
      ...enriched,
      bookingUrl: links.googleHotels, // Primary CTA → Google Hotels (always works, aggregates all OTAs)
    };
  });
}
